### ISSUE TITLE
LilyGoWatch.h is missing

### ISSUE THREAD

**Issue by Derek-is-Eric** [AlexGoodyear/agoodWatch#1]
Hi,
im trying to test this on my TTgo Watch 2020 but the Arduino IDE throws this error:

_config.h:10:25: error: LilyGoWatch.h: No such file or directory
compilation terminated.
exit status 1
LilyGoWatch.h: No such file or directory_

Could you give me a hint what i've had to do to solve this problem?

**Comment by AlexGoodyear** [comment]
You have to install the LilyGo TTGO_TWatch_Library first. Follow the install instructions at https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library. Note only install using the zip method or the clone method, not both!
