### ISSUE TITLE
error: 'lv_page_get_scrollable' was not declared in this scope

### ISSUE THREAD

**Issue by Pieksma** [AlexGoodyear/agoodWatch#12]
I get this error on compiling;
Arduino:1.8.13 (Windows Store 1.8.42.0) (Windows 10), Kort:"TTGO T-Watch, Enabled, Default (2 x 6.5 MB app, 3.6 MB SPIFFS), 115200, None"

sketch\gui.cpp: In member function 'void Keyboard::create(lv_obj_t*)':

gui.cpp:984:52: error: 'lv_page_get_scrollable' was not declared in this scope

         lv_obj_set_x(lv_page_get_scrollable(_kbPage), 0);

                                                    ^

sketch\gui.cpp: In static member function 'static void Keyboard::__kb_event_cb(lv_obj_t*, lv_event_t)':

gui.cpp:1016:94: error: 'lv_page_get_scrollable' was not declared in this scope

             lv_page_scroll_hor(_kb->_kbPage, lv_obj_get_x(lv_page_get_scrollable(_kb->_kbPage)) - 240);

                                                                                              ^

gui.cpp:1021:94: error: 'lv_page_get_scrollable' was not declared in this scope

             lv_page_scroll_hor(_kb->_kbPage, lv_obj_get_x(lv_page_get_scrollable(_kb->_kbPage)) *-1);

**Comment by AlexGoodyear** [comment]
You are using a very old version the Xinyuan LilyGO TTGO_TWatch library which in turn uses an old version of LVGL (v6). Update to the latest version of the Xinyuan LilyGO TTGO_TWatch uses v7 of the LVGL library.
