### ISSUE TITLE
Mqtt Feature if Possible

### ISSUE THREAD

**Issue by kcam01** [AlexGoodyear/agoodWatch#3]
If possible could you add a mqtt feature. I would love to track my steps in home assistant

**Comment by AlexGoodyear** [comment]
I have a personal roadmap of features that I want to implement that unfortunately doesn't include MQTT. In some preliminary WiFi experiments I found battery drain to be very high so I have shelved any WiFi orientated development for the foreseeable future.

**Comment by careyer** [comment]
+1 on a MQTT feature! =D

Thank you for the terrific work on this! This is really awesome! Keep up the good work!

Regarding your concerns about battery drainage with WiFi:
It could be a solution to only drop stats once a day via MQTT or on demand (like pressing a button, or when charging). This way it can easily be controled how often the Watch connects to the MQTT broker and conviniently offloads all of its data. ;-)
I am using MQTT in conjunction with Node RED, IndluxDB and Grafana on a Raspberry Pi and it works like a charm. Would be nice to see support for it in your Sketch! ;-)

Again! Amazing work! Keep it up!
