### ISSUE TITLE
Name of the day

### ISSUE THREAD

**Issue by Altron-2k20** [AlexGoodyear/agoodWatch#6]
Hello!

First of all: nice fork!

https://github.com/AlexGoodyear/agoodWatch/blob/fa4a4edbeace447f8317b852bde0991b0b29d382/agoodWatch/gui.cpp#L441

Just wanted to let you know that you can have the name of the day directly from the strftime() call with the paramenter %a. This will save you the map of the days with the array lookup.

**Comment by AlexGoodyear** [comment]
Yes, I had already spotted that in another project and pencilled it in to be changed in the next release. Thank you for your suggestion.
